accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: true
batch_norm: false
batch_size: 64
benchmark: false
beta: 0.001
check_val_every_n_epoch: 1
checkpoint_callback: true
class_weights:
- 1.0
- 1.0
compute_comparison_metrics: false
data_classes: 2
data_dims: !!python/tuple
- 1
- 128
- 128
dataset: lidc
default_root_dir: null
deterministic: false
distributed_backend: null
dropout: false
dropout_prob: 0.5
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_val: 0
latent_space_dim: 6
learning_rate: 0.0001
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 20
max_steps: null
min_epochs: 1
min_steps: null
model: softm
notest: false
num_filters:
- 32
- 64
- 128
- 192
num_iters: 100
num_models: 4
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse_utils._gpus_arg_default ''
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
weight_decay: 0
weights_save_path: null
weights_summary: top
